CREATE DATABASE IF NOT EXISTS feedback_db;
USE feedback_db;
CREATE TABLE IF NOT EXISTS feedback (id INT AUTO_INCREMENT PRIMARY KEY, student_name VARCHAR(100) NOT NULL, course_name VARCHAR(100) NOT NULL, rating INT NOT NULL, comments TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);